# Web site staging services:
staging:
  profile: ~
  whoami: master
  foo: trigger

publish:
  whoami: asf-site

notifications:
  commits: commits@tubemq.apache.org
  issues: commits@tubemq.apache.org
  pullrequests_status: commits@tubemq.apache.org
  pullrequests_comment: commits@tubemq.apache.org
  issues_status: dev@tubemq.apache.org
  issues_comment: commits@tubemq.apache.org
  jira_options: link label worklog